Xavierlibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('new_manager/', user_views.manager, name='new_manager'),
    path('profile/', user_views.profile, name='profile'),
    path('profile/changepass/', user_views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('library.urls')),
]

if settings.DEBUG:
	urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from .views import BookListView, BookDetailView,BookCreateView, BookSearchView, CommentCreateView, BookUpdateView, BookDeleteView, BookInstanceCreateView, BookInstanceUpdateView, BookInstanceDeleteView, AuthorListView, BookInstanceBorrowUpdateView, BookInstanceReturnUpdateView, AuthorCreateView, LogEntryListView, AuthorDetailView
from.import views

urlpatterns = [
    path('', BookListView.as_view(), name='library-home'), #path('', views.home, name='library-home'),
    path('about/', views.about, name='library-about'),
    path('search/', BookSearchView.as_view(), name='library-search'),
    path('author/', AuthorListView.as_view(), name='author-list'),
    path('logentry/',LogEntryListView.as_view(), name= 'log-entry'),
    path('book/<int:pk>/',BookDetailView.as_view(), name='book-detail'),#path('book/<book>',views.book, name='library-book'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('book/<int:pk>/edit/',BookUpdateView.as_view(), name='book-edit'),
    path('book/<int:pk>/delete/',BookDeleteView.as_view(), name='book-delete'),
    path('book/<int:pk>/addinstance/',BookInstanceCreateView.as_view(), name='bookinstance-add'),
    path('book/<int:book_id>/bookinstance/<pk>/edit/',BookInstanceUpdateView.as_view(), name='bookinstance-edit'),
    path('book/<int:book_id>/bookinstance/<pk>/delete/',BookInstanceDeleteView.as_view(), name='bookinstance-delete'),
    path('book/<int:book_id>/bookinstance/<pk>/borrow/',BookInstanceBorrowUpdateView.as_view(), name='bookinstance-Borrow'),
    #path('book/<int:book_id>/bookinstance/<pk>/return/',BookInstanceReturnUpdateView.as_view(), name='bookinstance-Return'),
    path('book/add/',BookCreateView.as_view(),name='book-create'),
    path('author/add/',AuthorCreateView.as_view(),name='author-create'),
    path('book/<int:pk>/comment/',CommentCreateView.as_view(),name='comment-create'),#path('book/comment/',CommentCreateView.as_view(),name='comment-create'),
]

library/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length = 100)
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

#Testing Library Model
from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

class comment(models.Model):
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    comment = models.TextField(max_length=1000, help_text="Enter a Comment")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.book.pk})

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.comment


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    call = models.CharField('Call Number', max_length=3, help_text="Enter a 3 digit call number", null=True)
    year = models.CharField('Year of Publication', max_length=4, help_text="Enter the year of publication", null=False)

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique book instances
from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, help_text="YYYY-MM-DD")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    """('d', 'Maintenance'),"""
    """('o', 'On loan'),"""

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk': self.book.pk})   

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

library/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from datetime import datetime, timedelta
#testing
from .models import Post
from .models import Author, Genre, Book, BookInstance, Language, comment
from users.models import Activity
#testing(1)
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE


books = [
	{
		'author': 'Lorenzo',
		'title': 'hello1',
		'content': 'heckyah',
		'date_posted': 'March 2, 2020'
	},
	{
		'author': 'Santi',
		'title': 'hello2',
		'content': 'heckyahzzz',
		'date_posted': 'March 4, 2020'
	},
]


# Create your views here.
def home(request):
	#context = {
	#	'books': Post.objects.all()
	#}
	context = {
		'books': Book.objects.all()
	}
	return render(request, 'library/home.html',context)

class BookListView(ListView):
	model = Book
	template_name = 'library/home.html'
	context_object_name = 'books'

class BookDetailView(DetailView):
	model = Book

class LogEntryListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
	model = Activity
	template_name = 'library/logentry.html'
	context_object_name = 'activities'

	def test_func(self):
		if str(self.request.user.profile.Role) == "Administrator":
			return True
		return False


class AuthorCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = Author
	fields = ['first_name','last_name','date_of_birth','date_of_death']

	def form_valid(self, form):
		message = 'Created new author "' + form.instance.last_name + ', ' + form.instance.first_name + '"'
		updateActivity(self.request.user.profile, 'Addition', message)
		return super(AuthorCreateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False


class BookCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = Book
	fields = ['title','author','summary','isbn','genre','language','call','year']

	def form_valid(self, form):
		message = 'Created new book "' + form.instance.title + '"'
		updateActivity(self.request.user.profile, 'Addition', message)
		return super(BookCreateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False

class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Book
	fields = ['title','author','summary','isbn','genre','language','call']

	def form_valid(self, form):
		message = 'Updated book "' + form.instance.title + '"'
		updateActivity(self.request.user.profile, 'Update', message)
		return super(BookUpdateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False

class BookDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Book
	success_url = '/'

	def form_valid(self, form):
		message = 'Deleted book "' + form.instance.title + '"'
		updateActivity(self.request.user.profile, 'Deletion', message)
		return super(BookDeleteView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False

class BookInstanceCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = BookInstance
	fields = ['imprint','status']
	#to pass book field to bookinstance
	def form_valid(self, form):
		book = Book.objects.get(pk=self.kwargs['pk'])
		form.instance.book = book
		message = 'Created book instance "' + form.instance.book.title + '"'
		updateActivity(self.request.user.profile, 'Addition', message)
		return super(BookInstanceCreateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False

class BookInstanceUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = BookInstance
	fields = ['imprint','status','due_back','borrower']

	#def form_valid(self, form):
		#book = Book.objects.get(pk=self.kwargs['bookinstance_id'])
		#form.instance.book = book
		#return super(BookInstanceUpdateView, self).form_valid(form)

	#def form_valid(self, form):
		#id = BookInstance.objects.get(pk=self.kwargs['pk'])
		#form.instance.id = id
		#return super(BookInstanceUpdateView, self).form_valid(form)
	def form_valid(self, form):
		message = 'Updated book instance "' + form.instance.book.title + '"'
		updateActivity(self.request.user.profile, 'Update', message)
		return super(BookInstanceUpdateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False		

class BookInstanceDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = BookInstance
	success_url = '/'

	def form_valid(self, form):
		message = 'Deleted book instance "' + form.instance.book.title + '"'
		updateActivity(self.request.user.profile, 'Deletion', message)
		return super(BookInstanceDeleteView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Book Manager":
			return True
		return False

class BookInstanceBorrowUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = BookInstance
	fields = []
	template_name = 'library/bookinstanceborrow_form.html'


	def form_valid(self, form):
		form.instance.status = 'r'
		form.instance.due_back = datetime.now() + timedelta(days=7)
		form.instance.borrower = self.request.user
		message = 'Borrowed book "' + form.instance.book.title + '" due back on ' + (form.instance.due_back.strftime("%d %B, %Y"))
		updateActivity(self.request.user.profile, 'Update', message)
		return super(BookInstanceBorrowUpdateView, self).form_valid(form)


	def test_func(self):
		if str(self.request.user.profile.Role) == "Student" or str(self.request.user.profile.Role) == "Teacher":
			return True		
		return False	

class BookInstanceReturnUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = BookInstance
	fields = []

	def form_valid(self, form):
		form.instance.status = 'a'
		form.instance.borrower = None
		form.instance.due_back = None
		message = 'Returned book "' + form.instance.book.title + '"'
		updateActivity(self.request.user.profile, 'Update', message)
		return super(BookInstanceReturnUpdateView, self).form_valid(form)


	def test_func(self):
		if str(self.request.user.profile.Role) == "Student" or str(self.request.user.profile.Role) == "Teacher":
			return True
		return False	


class CommentCreateView(LoginRequiredMixin, UserPassesTestMixin ,CreateView):
	model = comment
	fields = ['comment']

	def form_valid(self, form):
		book = Book.objects.get(pk=self.kwargs['pk'])
		form.instance.author = self.request.user
		form.instance.book = book
		message = 'Commented "' + form.instance.comment + '" on book "' + form.instance.book.title + '"'
		updateActivity(self.request.user.profile, 'Addition', message)

		return super(CommentCreateView, self).form_valid(form)

	def test_func(self):
		if str(self.request.user.profile.Role) == "Student" or str(self.request.user.profile.Role) == "Teacher":
			return True
		return False


def about(request):
	return render(request, 'library/about.html',{'title':'About'})

class BookSearchView(ListView):
	model = Book
	template_name = 'library/search.html'
	context_object_name = 'books'

class AuthorListView(ListView):
	template_name = 'library/author.html'
	context_object_name = 'authors'
	model = Author

class AuthorDetailView(DetailView):
	model = Author

def updateActivity(user, action, content):
	newactivity = Activity(
		user = user,
		action = action,
		content = content,
	)
	newactivity.save()

#def book(request,book):
#	book = Book.objects.get(title=book)
#	comments = book
	#book = Book.objects.filter(title=book).first()
	#context = {
	#	'comments': comment.objects.all()
	#}
#	return render(request, 'library/book.html',{'book':book})
	#return HttpResponse('<h1>This is the profile page! The user is {}.</h1>'.format(book))
	

library/templates/library/BookInstanceBorrow_form.html
{% extends "library/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Confirm borrowing this book?</legend>
					{{form|crispy}}
			</fieldset>
			<div class="form-group">
				<button class = "btn btn-outline-info" type="submit">Borrow</button>
			</div>
		</form>
	</div>
{% endblock content %}

library/templates/library/author.html
{% extends "library/base.html" %}
{% block content%}

    {% for author in authors %}
        <article class="media content-section" style="display: block">
            <div class="article-metadata">
                <a href="{% url 'author-detail' author.id %}">{{ author }}</a>
            </div>
		</article>
    {% endfor %}

{% endblock content %}

library/templates/library/author_detail.html
{% extends "library/base.html" %}
{% block content%}

<article class="media content-section" style="display: block">
    <h2 class="mr-2">{{ object.last_name }}, {{object.first_name}}</h2>
</article>
<div style="margin-left:20px;margin-top:20px">
<h4>Information:</h4>
<hr>
<article class="media content-section" style="display: block">
    <p class="article-content"><strong>First Name: </strong>{{ object.first_name }}</p>
    <p class="article-content"><strong>Last Name: </strong>{{ object.last_name }}</p>
    <p class="article-content"><strong>Date of Birth: </strong>{{ object.date_of_birth }}</p>
    <p class="article-content"><strong>Date of Death: </strong>{{ object.date_of_death }}</p>
</article>

<h4>Books by this author:</h4>
<hr>
<article class="media content-section" style="display: block">
    {% for book in author.book_set.all %}
    <a class="article-title" href="{% url 'book-detail' book.id %}">{{ book.title }}</a><br>
    {% endfor %}
</article>
</div>

{% endblock content %}

library/templates/library/author_form.html
{% extends "library/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Add Author</legend>
					{{form|crispy}}
			</fieldset>
			<div class="form-group">
				<button class = "btn btn-outline-info" type="submit">Add</button>
			</div>
		</form>
	</div>
{% endblock content %}

library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'library/main.css' %}">

	{% if title %}
	<title>HomePage - {{ title}}</title>
	{% else %}
	<title>HomePage</title>
	{% endif %}

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'library-home'%}">Xavier Library</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'library-home'%}">Home</a>
	          <a class="nav-item nav-link" href="{% url 'library-about'%}">About</a>
	          {% if not user.is_authenticated or user.profile.Role.browse_search %}
	          <a class="nav-item nav-link" href="{% url 'library-search'%}">Find a Book</a>
	          <a class="nav-item nav-link" href="{% url 'author-list'%}">List of Authors</a>
	          {% endif %}
	          {% if user.profile.Role.add %}
	          <a class="nav-item nav-link" href="{% url 'book-create'%}">Add a Book</a>
	          <a class="nav-item nav-link" href="{% url 'author-create'%}">Add a Author</a>
	          {% endif %}
	          {% if user.profile.Role.create_manager %}
	          <a class="nav-item nav-link" href="{% url 'new_manager' %}">Create a new Manager</a>
	          <a class="nav-item nav-link" href="{% url 'log-entry' %}">Check Activity Logs</a>
	          {% endif %}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if user.is_authenticated  %}
	        		{% if user.profile.Role.borrow %}
	        		<a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
	        		{% endif %}
	        		<a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
	        	{% else %}
	          		<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
	          		<a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
	          	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% if messages %}
	    		{% for message in messages %}
	    			<div class="alert alert-{{message.tags}}">
	    				{{message}}
	    			</div>
	    		{% endfor %}
			{% endif %}
	      {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	    </div>
	  </div>
	</main>

</body>
</html>

library/templates/library/book_confirm_delete.html
{% extends "library/base.html" %}
{% block content%}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Remove Book</legend>
				<h2>Are you sure you want to remove book "{{ object.title }}"</h2>
			</fieldset>
			<div class="form-group">
				<button class = "btn btn-outline-danger" type="submit">Yes, Remove</button>
				<a class = "btn btn-outline-secondary" href="{% url 'book-detail' object.id %}">Cancel</a>
			</div>
		</form>
	</div>
{% endblock content %}

library/templates/library/book_detail.html
{% extends "library/base.html" %}

{% block content%}

			<article class="media content-section">
			  <div class="media-body">
			    <div class="article-metadata">
			      <a class="mr-2" href="{% url 'author-detail' object.author.id %}">{{ object.author }}</a>
			      <small class="text-muted">{{ object.isbn }}</small>
			      {% if user.profile.Role.edit %}
			      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'book-edit' object.id%}">Edit</a>
			      {% endif %}
			      {% if user.profile.Role.delete %}
			      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'book-delete' object.id%}">Remove</a>
			      {% endif %}
			    </div>
			    <h2 class="article-title">{{ object.title }}</h2>
				<p class="article-content">{{ object.summary }}</p>
				<hr style="border-color: gray;">
			    <p class="article-content"><strong>Language: </strong>{{ object.language }}</p>
			    <p class="article-content"><strong>Genre: </strong>{{ object.display_genre }}</p>
			    <p class="article-content"><strong>Call: </strong>{{ object.call }}</p>
			    <p class="article-content"><strong>Year of Publication: </strong>{{ object.year }}</p>
			  </div>
			 </article>

			  <div style="margin-left:20px;margin-top:20px">
				<h4>Copies</h4>
				<hr>
			    {% if user.profile.Role.add_instance %}
			    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bookinstance-add' object.id%}">Add Instance</a>
			    {% endif %}
			    

			    {% for copy in object.bookinstance_set.all %}
			      {% if user.profile.Role.edit_instance %}
			      <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bookinstance-edit' object.id copy.pk%}">Edit</a>
			      {% endif %}

			      {% if copy.status == 'a' %}
			      	{% if user.profile.Role.borrow %}
			     		<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bookinstance-Borrow' object.id copy.pk%}">Borrow</a>
			      	{% endif %}
			      {% endif %}
			     
			     
			      {% if user.profile.Role.delete %}
			      <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'bookinstance-delete' object.id copy.pk%}">Remove</a>
				  {% endif %}
				  <article class="media content-section" style="display: block;">
			      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
			        {{ copy.get_status_display }}
				  </p>
				 <hr style="border-color: gray;">
			      {% if copy.status != 'a' %}
			        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
			      {% endif %}
			      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
				  <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
				</article>
				  <hr>
				{% endfor %}
			  </div>
			<!--</article>-->

			<div style="margin-left:20px;margin-top:20px">
				<div style="display: flex;">
			    <h4>Review</h4>
				<hr>
			    <div class="form-group">
					{% if user.profile.Role.review %}
					<a class="mr-2" href="{% url 'comment-create' object.id %}">Review This Book</a>
					{% endif %}
				</div>
				</div>
				<hr>
				{% for comment in book.comment_set.all %}
				<article class="media content-section" style="display: block;">
				  <p><strong>{{ comment.comment }}</strong></p>
				  <hr style="border-color: gray;">
				  <p class="text-muted"><strong>User:</strong> {{ comment.author }}</p>
				</article>
				{% endfor %}
				<hr>
			  </div>
			<!-- </article> -->

{% endblock content %}

<!-- Write your comments here -->
<!-- href="/book/{{ book.title }}" -->

library/templates/library/book_form.html
{% extends "library/base.html" %}
{% load crispy_forms_tags %}
{% block content%}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Add book</legend>
					{{form|crispy}}
			</fieldset>
			<div class="form-group">
				<button class = "btn btn-outline-info" type="submit">Add</button>
			</div>
		</form>
	</div>
{% endblock content %}